plugin: aws_ec2
regions:
  - eu-north-1
host_key_checks: False
keyed_groups:
  - key: tags.Name
    prefix: ansible_server
    separator: _
compose:
  ansible_host: public_ip_address  # <-- This is the fix!
