---
- name: Update and upgrade apt packages (Debian/Ubuntu)
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Update and upgrade yum packages (RedHat/CentOS)
  yum:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"
